# Generated by Django 3.0.7 on 2020-06-14 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tweet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tweetID', models.IntegerField()),
                ('url', models.URLField()),
                ('imageUrl', models.ImageField(upload_to=None)),
                ('imageInfo', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='TweetTopico',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tweetID', models.IntegerField()),
                ('feeling', models.TextField()),
                ('feelingNum', models.DecimalField(decimal_places=2, max_digits=2)),
                ('averageLikes', models.DecimalField(decimal_places=2, max_digits=2)),
                ('averageRetweets', models.DecimalField(decimal_places=2, max_digits=2)),
                ('averageComments', models.DecimalField(decimal_places=2, max_digits=2)),
                ('averageProfanity', models.DecimalField(decimal_places=2, max_digits=2)),
                ('keywords', models.TextField()),
            ],
        ),
    ]
