# Generated by Django 3.0.7 on 2020-06-14 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PEIAPI', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TweetTopic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tweetID', models.IntegerField()),
                ('feeling', models.TextField()),
                ('feelingFinal', models.TextField()),
                ('feelingNegative', models.DecimalField(decimal_places=2, max_digits=2)),
                ('feelingPositive', models.DecimalField(decimal_places=2, max_digits=2)),
                ('averageLikes', models.DecimalField(decimal_places=2, max_digits=2)),
                ('averageRetweets', models.DecimalField(decimal_places=2, max_digits=2)),
                ('averageComments', models.DecimalField(decimal_places=2, max_digits=2)),
                ('averageProfanity', models.DecimalField(decimal_places=2, max_digits=2)),
                ('keywords', models.TextField()),
            ],
        ),
        migrations.DeleteModel(
            name='TweetTopico',
        ),
    ]
