# Generated by Django 3.0.7 on 2020-06-16 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PEIAPI', '0002_auto_20200614_1542'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tweettopic',
            name='averageComments',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='tweettopic',
            name='averageLikes',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='tweettopic',
            name='averageRetweets',
            field=models.IntegerField(),
        ),
    ]
